# Generated by Django 5.0.1 on 2026-01-06 23:36

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('airport_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Tags like: sunny, adventure, party, family, romantic', size=None)),
                ('highlights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Key attractions or things the city is known for', size=None)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, help_text='Average flight price in EUR', max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'db_table': 'destinations',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='DestinationTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#0ca4eb', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination Tag',
                'verbose_name_plural': 'Destination Tags',
                'db_table': 'destination_tags',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BestBookingTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_before_departure', models.IntegerField(help_text='Optimal days before departure to book')),
                ('best_day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Best day to book', null=True)),
                ('best_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Best month to travel', null=True)),
                ('average_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Average savings percentage', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_times', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Best Booking Time',
                'verbose_name_plural': 'Best Booking Times',
                'db_table': 'best_booking_times',
            },
        ),
    ]
