# Generated by Django 5.0.1 on 2026-01-07 00:18

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iata_code', models.CharField(help_text='IATA code (e.g., 738)', max_length=3, unique=True)),
                ('icao_code', models.CharField(blank=True, help_text='ICAO code (e.g., B738)', max_length=4)),
                ('name', models.CharField(help_text='e.g., Boeing 737-800', max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('typical_seats', models.IntegerField(blank=True, null=True)),
                ('range_km', models.IntegerField(blank=True, null=True)),
                ('cruise_speed_kmh', models.IntegerField(blank=True, null=True)),
                ('aircraft_type', models.CharField(choices=[('narrow_body', 'Narrow Body'), ('wide_body', 'Wide Body'), ('regional', 'Regional')], default='narrow_body', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'db_table': 'aircraft',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iata_code', models.CharField(db_index=True, help_text='2-letter IATA code (e.g., FR)', max_length=2, unique=True)),
                ('icao_code', models.CharField(blank=True, help_text='3-letter ICAO code (e.g., RYR)', max_length=3, null=True, unique=True)),
                ('name', models.CharField(help_text='Airline name (e.g., Ryanair)', max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('logo_url', models.URLField(blank=True, help_text='URL to airline logo', max_length=500)),
                ('primary_color', models.CharField(blank=True, help_text='Hex color (e.g., #003366)', max_length=7)),
                ('airline_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('charter', 'Charter'), ('cargo', 'Cargo'), ('low_cost', 'Low Cost')], default='scheduled', max_length=50)),
                ('alliance', models.CharField(blank=True, choices=[('', 'None'), ('Star Alliance', 'Star Alliance'), ('Oneworld', 'Oneworld'), ('SkyTeam', 'SkyTeam')], max_length=50)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('hub_airports', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, default=list, help_text='Hub airport IATA codes', size=None)),
                ('fleet_size', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_low_cost', models.BooleanField(default=False)),
                ('rating', models.FloatField(blank=True, help_text='1-5 scale', null=True)),
                ('on_time_performance', models.FloatField(blank=True, help_text='Percentage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Airline',
                'verbose_name_plural': 'Airlines',
                'db_table': 'airlines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iata_code', models.CharField(db_index=True, help_text='3-letter IATA code (e.g., DUB)', max_length=3, unique=True)),
                ('icao_code', models.CharField(blank=True, help_text='4-letter ICAO code (e.g., EIDW)', max_length=4, null=True, unique=True)),
                ('name', models.CharField(help_text='Airport name (e.g., Dublin Airport)', max_length=255)),
                ('city', models.CharField(help_text='City name', max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('country_code', models.CharField(db_index=True, help_text='ISO 2-letter country code', max_length=2)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, help_text='e.g., Europe/Dublin', max_length=50)),
                ('altitude_ft', models.IntegerField(blank=True, null=True)),
                ('airport_type', models.CharField(choices=[('airport', 'Airport'), ('heliport', 'Heliport'), ('seaplane_base', 'Seaplane Base')], default='airport', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_major', models.BooleanField(default=False, help_text='Major international airport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'db_table': 'airports',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='metadata',
            new_name='extra_data',
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_code', models.CharField(db_index=True, help_text='Origin airport IATA code', max_length=3)),
                ('destination_code', models.CharField(db_index=True, help_text='Destination airport IATA code', max_length=3)),
                ('airline_code', models.CharField(blank=True, help_text='Operating airline IATA code', max_length=2)),
                ('is_direct', models.BooleanField(default=True)),
                ('typical_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.IntegerField(blank=True, null=True)),
                ('flights_per_week', models.IntegerField(blank=True, null=True)),
                ('operates_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Days of week (1=Mon, 7=Sun)', size=None)),
                ('typical_price_low', models.FloatField(blank=True, help_text='Low season economy price', null=True)),
                ('typical_price_high', models.FloatField(blank=True, help_text='High season economy price', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seasonal', models.BooleanField(default=False)),
                ('season_start', models.IntegerField(blank=True, help_text='Start month (1-12)', null=True)),
                ('season_end', models.IntegerField(blank=True, help_text='End month (1-12)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'routes',
                'ordering': ['origin_code', 'destination_code'],
                'unique_together': {('origin_code', 'destination_code', 'airline_code')},
            },
        ),
    ]
