# Generated by Django 5.0.1 on 2026-01-06 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('search', 'Flight Search'), ('view_results', 'View Results'), ('select_flight', 'Select Flight'), ('click_affiliate', 'Click Affiliate Link'), ('create_trip', 'Create Trip'), ('invite_member', 'Invite Trip Member'), ('set_alert', 'Set Price Alert')], max_length=50)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('affiliate', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Conversion Event',
                'verbose_name_plural': 'Conversion Events',
                'db_table': 'conversion_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_searches', models.IntegerField(default=0)),
                ('unique_routes_searched', models.IntegerField(default=0)),
                ('trips_created', models.IntegerField(default=0)),
                ('trip_members_added', models.IntegerField(default=0)),
                ('alerts_created', models.IntegerField(default=0)),
                ('alerts_triggered', models.IntegerField(default=0)),
                ('affiliate_clicks', models.IntegerField(default=0)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('cache_hit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Metrics',
                'verbose_name_plural': 'Daily Metrics',
                'db_table': 'daily_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PopularRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_code', models.CharField(db_index=True, max_length=10)),
                ('destination_code', models.CharField(db_index=True, max_length=10)),
                ('period_type', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('search_count', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('rank_change', models.IntegerField(default=0, help_text='Change from previous period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Popular Route',
                'verbose_name_plural': 'Popular Routes',
                'db_table': 'popular_routes',
                'ordering': ['-period_start', 'rank'],
                'unique_together': {('origin_code', 'destination_code', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_code', models.CharField(db_index=True, max_length=10)),
                ('destination_code', models.CharField(db_index=True, max_length=10)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passengers', models.IntegerField(default=1)),
                ('cabin_class', models.CharField(blank=True, max_length=50)),
                ('results_count', models.IntegerField(default=0)),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_country', models.CharField(blank=True, max_length=2)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'db_table': 'search_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['origin_code', 'destination_code'], name='search_logs_origin__500ff1_idx'), models.Index(fields=['created_at'], name='search_logs_created_1842c5_idx')],
            },
        ),
    ]
