# Generated by Django 5.0.1 on 2026-01-06 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube')], max_length=20)),
                ('content_id', models.CharField(help_text='Platform-specific content ID', max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('caption', models.TextField(blank=True)),
                ('creator', models.CharField(blank=True, max_length=255)),
                ('creator_url', models.URLField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('destination_code', models.CharField(db_index=True, max_length=10)),
                ('destination_name', models.CharField(blank=True, max_length=255)),
                ('views', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('moderation_notes', models.TextField(blank=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Content',
                'verbose_name_plural': 'Social Content',
                'db_table': 'social_content',
                'ordering': ['-scraped_at'],
                'unique_together': {('platform', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='ContentCuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('destination_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_curations', to=settings.AUTH_USER_MODEL)),
                ('content_items', models.ManyToManyField(blank=True, related_name='curations', to='content.socialcontent')),
            ],
            options={
                'verbose_name': 'Content Curation',
                'verbose_name_plural': 'Content Curations',
                'db_table': 'content_curations',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
